name: stream
channels:
  - conda-forge
dependencies:
  - python
  - python-dotenv
  - pyinstaller
  - pip
  - pip:
      - cachetools
      - flet
      - pycountry
      - simple-justwatch-python-api
