export const COUNTRIES: Record<string, string> = {
  AF: "🇦🇫 Afghanistan",
  AX: "🇦🇽 Åland Islands",
  AL: "🇦🇱 Albania",
  DZ: "🇩🇿 Algeria",
  AS: "🇦🇸 American Samoa",
  AD: "🇦🇩 Andorra",
  AO: "🇦🇴 Angola",
  AI: "🇦🇮 Anguilla",
  AQ: "🇦🇶 Antarctica",
  AG: "🇦🇬 Antigua and Barbuda",
  AR: "🇦🇷 Argentina",
  AM: "🇦🇲 Armenia",
  AW: "🇦🇼 Aruba",
  AU: "🇦🇺 Australia",
  AT: "🇦🇹 Austria",
  AZ: "🇦🇿 Azerbaijan",
  BS: "🇧🇸 Bahamas",
  BH: "🇧🇭 Bahrain",
  BD: "🇧🇩 Bangladesh",
  BB: "🇧🇧 Barbados",
  BY: "🇧🇾 Belarus",
  BE: "🇧🇪 Belgium",
  BZ: "🇧🇿 Belize",
  BJ: "🇧🇯 Benin",
  BM: "🇧🇲 Bermuda",
  BT: "🇧🇹 Bhutan",
  BO: "🇧🇴 Bolivia (Plurinational State of)",
  BQ: "🇧🇶 Bonaire, Sint Eustatius and Saba",
  BA: "🇧🇦 Bosnia and Herzegovina",
  BW: "🇧🇼 Botswana",
  BV: "🇧🇻 Bouvet Island",
  BR: "🇧🇷 Brazil",
  IO: "🇮🇴 British Indian Ocean Territory",
  BN: "🇧🇳 Brunei Darussalam",
  BG: "🇧🇬 Bulgaria",
  BF: "🇧🇫 Burkina Faso",
  BI: "🇧🇮 Burundi",
  CV: "🇨🇻 Cabo Verde",
  KH: "🇰🇭 Cambodia",
  CM: "🇨🇲 Cameroon",
  CA: "🇨🇦 Canada",
  KY: "🇰🇾 Cayman Islands",
  CF: "🇨🇫 Central African Republic",
  TD: "🇹🇩 Chad",
  CL: "🇨🇱 Chile",
  CN: "🇨🇳 China",
  CX: "🇨🇽 Christmas Island",
  CC: "🇨🇨 Cocos (Keeling) Islands",
  CO: "🇨🇴 Colombia",
  KM: "🇰🇲 Comoros",
  CG: "🇨🇬 Congo",
  CD: "🇨🇩 Congo, Democratic Republic of the",
  CK: "🇨🇰 Cook Islands",
  CR: "🇨🇷 Costa Rica",
  HR: "🇭🇷 Croatia",
  CU: "🇨🇺 Cuba",
  CW: "🇨🇼 Curaçao",
  CY: "🇨🇾 Cyprus",
  CZ: "🇨🇿 Czechia",
  CI: "🇨🇮 Côte d'Ivoire",
  DK: "🇩🇰 Denmark",
  DJ: "🇩🇯 Djibouti",
  DM: "🇩🇲 Dominica",
  DO: "🇩🇴 Dominican Republic",
  EC: "🇪🇨 Ecuador",
  EG: "🇪🇬 Egypt",
  SV: "🇸🇻 El Salvador",
  GQ: "🇬🇶 Equatorial Guinea",
  ER: "🇪🇷 Eritrea",
  EE: "🇪🇪 Estonia",
  SZ: "🇸🇿 Eswatini",
  ET: "🇪🇹 Ethiopia",
  FK: "🇫🇰 Falkland Islands (Malvinas)",
  FO: "🇫🇴 Faroe Islands",
  FJ: "🇫🇯 Fiji",
  FI: "🇫🇮 Finland",
  FR: "🇫🇷 France",
  GF: "🇬🇫 French Guiana",
  PF: "🇵🇫 French Polynesia",
  TF: "🇹🇫 French Southern Territories",
  GA: "🇬🇦 Gabon",
  GM: "🇬🇲 Gambia",
  GE: "🇬🇪 Georgia",
  DE: "🇩🇪 Germany",
  GH: "🇬🇭 Ghana",
  GI: "🇬🇮 Gibraltar",
  GR: "🇬🇷 Greece",
  GL: "🇬🇱 Greenland",
  GD: "🇬🇩 Grenada",
  GP: "🇬🇵 Guadeloupe",
  GU: "🇬🇺 Guam",
  GT: "🇬🇹 Guatemala",
  GG: "🇬🇬 Guernsey",
  GN: "🇬🇳 Guinea",
  GW: "🇬🇼 Guinea-Bissau",
  GY: "🇬🇾 Guyana",
  HT: "🇭🇹 Haiti",
  HM: "🇭🇲 Heard Island and McDonald Islands",
  VA: "🇻🇦 Holy See",
  HN: "🇭🇳 Honduras",
  HK: "🇭🇰 Hong Kong",
  HU: "🇭🇺 Hungary",
  IS: "🇮🇸 Iceland",
  IN: "🇮🇳 India",
  ID: "🇮🇩 Indonesia",
  IR: "🇮🇷 Iran (Islamic Republic of)",
  IQ: "🇮🇶 Iraq",
  IE: "🇮🇪 Ireland",
  IM: "🇮🇲 Isle of Man",
  IL: "🇮🇱 Israel",
  IT: "🇮🇹 Italy",
  JM: "🇯🇲 Jamaica",
  JP: "🇯🇵 Japan",
  JE: "🇯🇪 Jersey",
  JO: "🇯🇴 Jordan",
  KZ: "🇰🇿 Kazakhstan",
  KE: "🇰🇪 Kenya",
  KI: "🇰🇮 Kiribati",
  KP: "🇰🇵 Korea (Democratic People's Republic of)",
  KR: "🇰🇷 Korea, Republic of",
  KW: "🇰🇼 Kuwait",
  KG: "🇰🇬 Kyrgyzstan",
  LA: "🇱🇦 Lao People's Democratic Republic",
  LV: "🇱🇻 Latvia",
  LB: "🇱🇧 Lebanon",
  LS: "🇱🇸 Lesotho",
  LR: "🇱🇷 Liberia",
  LY: "🇱🇾 Libya",
  LI: "🇱🇮 Liechtenstein",
  LT: "🇱🇹 Lithuania",
  LU: "🇱🇺 Luxembourg",
  MO: "🇲🇴 Macao",
  MG: "🇲🇬 Madagascar",
  MW: "🇲🇼 Malawi",
  MY: "🇲🇾 Malaysia",
  MV: "🇲🇻 Maldives",
  ML: "🇲🇱 Mali",
  MT: "🇲🇹 Malta",
  MH: "🇲🇭 Marshall Islands",
  MQ: "🇲🇶 Martinique",
  MR: "🇲🇷 Mauritania",
  MU: "🇲🇺 Mauritius",
  YT: "🇾🇹 Mayotte",
  MX: "🇲🇽 Mexico",
  FM: "🇫🇲 Micronesia (Federated States of)",
  MD: "🇲🇩 Moldova, Republic of",
  MC: "🇲🇨 Monaco",
  MN: "🇲🇳 Mongolia",
  ME: "🇲🇪 Montenegro",
  MS: "🇲🇸 Montserrat",
  MA: "🇲🇦 Morocco",
  MZ: "🇲🇿 Mozambique",
  MM: "🇲🇲 Myanmar",
  NA: "🇳🇦 Namibia",
  NR: "🇳🇷 Nauru",
  NP: "🇳🇵 Nepal",
  NL: "🇳🇱 Netherlands",
  NC: "🇳🇨 New Caledonia",
  NZ: "🇳🇿 New Zealand",
  NI: "🇳🇮 Nicaragua",
  NE: "🇳🇪 Niger",
  NG: "🇳🇬 Nigeria",
  NU: "🇳🇺 Niue",
  NF: "🇳🇫 Norfolk Island",
  MK: "🇲🇰 North Macedonia",
  MP: "🇲🇵 Northern Mariana Islands",
  NO: "🇳🇴 Norway",
  OM: "🇴🇲 Oman",
  PK: "🇵🇰 Pakistan",
  PW: "🇵🇼 Palau",
  PS: "🇵🇸 Palestine, State of",
  PA: "🇵🇦 Panama",
  PG: "🇵🇬 Papua New Guinea",
  PY: "🇵🇾 Paraguay",
  PE: "🇵🇪 Peru",
  PH: "🇵🇭 Philippines",
  PN: "🇵🇳 Pitcairn",
  PL: "🇵🇱 Poland",
  PT: "🇵🇹 Portugal",
  PR: "🇵🇷 Puerto Rico",
  QA: "🇶🇦 Qatar",
  RE: "🇷🇪 Réunion",
  RO: "🇷🇴 Romania",
  RU: "🇷🇺 Russian Federation",
  RW: "🇷🇼 Rwanda",
  BL: "🇧🇱 Saint Barthélemy",
  SH: "🇸🇭 Saint Helena, Ascension and Tristan da Cunha",
  KN: "🇰🇳 Saint Kitts and Nevis",
  LC: "🇱🇨 Saint Lucia",
  MF: "🇲🇫 Saint Martin (French part)",
  PM: "🇵🇲 Saint Pierre and Miquelon",
  VC: "🇻🇨 Saint Vincent and the Grenadines",
  WS: "🇼🇸 Samoa",
  SM: "🇸🇲 San Marino",
  ST: "🇸🇹 Sao Tome and Principe",
  SA: "🇸🇦 Saudi Arabia",
  SN: "🇸🇳 Senegal",
  RS: "🇷🇸 Serbia",
  SC: "🇸🇨 Seychelles",
  SL: "🇸🇱 Sierra Leone",
  SG: "🇸🇬 Singapore",
  SX: "🇸🇽 Sint Maarten",
  SK: "🇸🇰 Slovakia",
  SI: "🇸🇮 Slovenia",
  SB: "🇸🇧 Solomon Islands",
  SO: "🇸🇴 Somalia",
  ZA: "🇿🇦 South Africa",
  GS: "🇬🇸 South Georgia and the South Sandwich Islands",
  SS: "🇸🇸 South Sudan",
  ES: "🇪🇸 Spain",
  LK: "🇱🇰 Sri Lanka",
  SD: "🇸🇩 Sudan",
  SR: "🇸🇷 Suriname",
  SJ: "🇸🇯 Svalbard and Jan Mayen",
  SE: "🇸🇪 Sweden",
  CH: "🇨🇭 Switzerland",
  SY: "🇸🇾 Syrian Arab Republic",
  TW: "🇹🇼 Taiwan, Province of China",
  TJ: "🇹🇯 Tajikistan",
  TZ: "🇹🇿 Tanzania, United Republic of",
  TH: "🇹🇭 Thailand",
  TL: "🇹🇱 Timor-Leste",
  TG: "🇹🇬 Togo",
  TK: "🇹🇰 Tokelau",
  TO: "🇹🇴 Tonga",
  TT: "🇹🇹 Trinidad and Tobago",
  TN: "🇹🇳 Tunisia",
  TR: "🇹🇷 Türkiye",
  TM: "🇹🇲 Turkmenistan",
  TC: "🇹🇨 Turks and Caicos Islands",
  TV: "🇹🇻 Tuvalu",
  UG: "🇺🇬 Uganda",
  UA: "🇺🇦 Ukraine",
  AE: "🇦🇪 United Arab Emirates",
  GB: "🇬🇧 United Kingdom of Great Britain and Northern Ireland",
  US: "🇺🇸 United States of America",
  UM: "🇺🇲 United States Minor Outlying Islands",
  UY: "🇺🇾 Uruguay",
  UZ: "🇺🇿 Uzbekistan",
  VU: "🇻🇺 Vanuatu",
  VE: "🇻🇪 Venezuela (Bolivarian Republic of)",
  VN: "🇻🇳 Viet Nam",
  VG: "🇻🇬 Virgin Islands (British)",
  VI: "🇻🇮 Virgin Islands (U.S.)",
  WF: "🇼🇫 Wallis and Futuna",
  EH: "🇪🇭 Western Sahara",
  YE: "🇾🇪 Yemen",
  ZM: "🇿🇲 Zambia",
  ZW: "🇿🇼 Zimbabwe",
};

export const LANGUAGES: Record<string, string> = {
  af: "🇿🇦 Afrikaans",
  am: "🇪🇹 Amharic",
  ar: "🇸🇦 Arabic",
  az: "🇦🇿 Azerbaijani",
  be: "🇧🇾 Belarusian",
  bg: "🇧🇬 Bulgarian",
  bn: "🇧🇩 Bengali",
  bs: "🇧🇦 Bosnian",
  ca: "🇪🇸 Catalan",
  cs: "🇨🇿 Czech",
  cy: "🏴 Welsh",
  da: "🇩🇰 Danish",
  de: "🇩🇪 German",
  el: "🇬🇷 Greek",
  en: "🇬🇧 English",
  eo: "🌐 Esperanto",
  es: "🇪🇸 Spanish",
  et: "🇪🇪 Estonian",
  eu: "🇪🇸 Basque",
  fa: "🇮🇷 Persian",
  fi: "🇫🇮 Finnish",
  fj: "🇫🇯 Fijian",
  fo: "🇫🇴 Faroese",
  fr: "🇫🇷 French",
  fy: "🇳🇱 Western Frisian",
  ga: "🇮🇪 Irish",
  gd: "🏴 Scottish Gaelic",
  gl: "🇪🇸 Galician",
  gu: "🇮🇳 Gujarati",
  he: "🇮🇱 Hebrew",
  hi: "🇮🇳 Hindi",
  hr: "🇭🇷 Croatian",
  ht: "🇭🇹 Haitian Creole",
  hu: "🇭🇺 Hungarian",
  hy: "🇦🇲 Armenian",
  id: "🇮🇩 Indonesian",
  is: "🇮🇸 Icelandic",
  it: "🇮🇹 Italian",
  ja: "🇯🇵 Japanese",
  jv: "🇮🇩 Javanese",
  ka: "🇬🇪 Georgian",
  kk: "🇰🇿 Kazakh",
  km: "🇰🇭 Khmer",
  kn: "🇮🇳 Kannada",
  ko: "🇰🇷 Korean",
  ku: "🇹🇷 Kurdish",
  ky: "🇰🇬 Kyrgyz",
  la: "🏛️ Latin",
  lb: "🇱🇺 Luxembourgish",
  lo: "🇱🇦 Lao",
  lt: "🇱🇹 Lithuanian",
  lv: "🇱🇻 Latvian",
  mg: "🇲🇬 Malagasy",
  mk: "🇲🇰 Macedonian",
  ml: "🇮🇳 Malayalam",
  mn: "🇲🇳 Mongolian",
  mr: "🇮🇳 Marathi",
  ms: "🇲🇾 Malay",
  mt: "🇲🇹 Maltese",
  my: "🇲🇲 Burmese",
  nb: "🇳🇴 Norwegian Bokmål",
  ne: "🇳🇵 Nepali",
  nl: "🇳🇱 Dutch",
  nn: "🇳🇴 Norwegian Nynorsk",
  no: "🇳🇴 Norwegian",
  or: "🇮🇳 Odia",
  pa: "🇮🇳 Punjabi",
  pl: "🇵🇱 Polish",
  ps: "🇦🇫 Pashto",
  pt: "🇵🇹 Portuguese",
  ro: "🇷🇴 Romanian",
  ru: "🇷🇺 Russian",
  rw: "🇷🇼 Kinyarwanda",
  se: "🇸🇪 Northern Sami",
  si: "🇱🇰 Sinhala",
  sk: "🇸🇰 Slovak",
  sl: "🇸🇮 Slovenian",
  sm: "🇼🇸 Samoan",
  sn: "🇿🇼 Shona",
  so: "🇸🇴 Somali",
  sq: "🇦🇱 Albanian",
  sr: "🇷🇸 Serbian",
  st: "🇱🇸 Southern Sotho",
  su: "🇮🇩 Sundanese",
  sv: "🇸🇪 Swedish",
  sw: "🇰🇪 Swahili",
  ta: "🇮🇳 Tamil",
  te: "🇮🇳 Telugu",
  tg: "🇹🇯 Tajik",
  th: "🇹🇭 Thai",
  ti: "🇪🇷 Tigrinya",
  tk: "🇹🇲 Turkmen",
  tl: "🇵🇭 Tagalog",
  tr: "🇹🇷 Turkish",
  tt: "🇷🇺 Tatar",
  ug: "🇨🇳 Uyghur",
  uk: "🇺🇦 Ukrainian",
  ur: "🇵🇰 Urdu",
  uz: "🇺🇿 Uzbek",
  vi: "🇻🇳 Vietnamese",
  wo: "🇸🇳 Wolof",
  xh: "🇿🇦 Xhosa",
  yi: "🇮🇱 Yiddish",
  zh: "🇨🇳 Chinese",
  zu: "🇿🇦 Zulu",
};

export const COUNTRY_LANGUAGE_MAP: Record<string, string> = {
  AF: "fa",
  AL: "sq",
  DZ: "ar",
  AD: "ca",
  AO: "pt",
  AG: "en",
  AR: "es",
  AM: "hy",
  AU: "en",
  AT: "de",
  AZ: "az",
  BS: "en",
  BH: "ar",
  BD: "bn",
  BB: "en",
  BY: "be",
  BE: "nl",
  BZ: "en",
  BJ: "fr",
  BT: "dz",
  BO: "es",
  BA: "bs",
  BW: "en",
  BR: "pt",
  BN: "ms",
  BG: "bg",
  BF: "fr",
  BI: "fr",
  KH: "km",
  CM: "fr",
  CA: "en",
  CV: "pt",
  CF: "fr",
  TD: "fr",
  CL: "es",
  CN: "zh",
  CO: "es",
  KM: "ar",
  CG: "fr",
  CR: "es",
  HR: "hr",
  CU: "es",
  CY: "el",
  CZ: "cs",
  DK: "da",
  DJ: "fr",
  DM: "en",
  DO: "es",
  EC: "es",
  EG: "ar",
  SV: "es",
  GQ: "es",
  ER: "ti",
  EE: "et",
  SZ: "en",
  ET: "am",
  FJ: "en",
  FI: "fi",
  FR: "fr",
  GA: "fr",
  GM: "en",
  GE: "ka",
  DE: "de",
  GH: "en",
  GR: "el",
  GD: "en",
  GT: "es",
  GN: "fr",
  GW: "pt",
  GY: "en",
  HT: "ht",
  HN: "es",
  HU: "hu",
  IS: "is",
  IN: "hi",
  ID: "id",
  IR: "fa",
  IQ: "ar",
  IE: "en",
  IL: "he",
  IT: "it",
  CI: "fr",
  JM: "en",
  JP: "ja",
  JO: "ar",
  KZ: "kk",
  KE: "sw",
  KI: "en",
  KP: "ko",
  KR: "ko",
  KW: "ar",
  KG: "ky",
  LA: "lo",
  LV: "lv",
  LB: "ar",
  LS: "en",
  LR: "en",
  LY: "ar",
  LI: "de",
  LT: "lt",
  LU: "lb",
  MG: "fr",
  MW: "en",
  MY: "ms",
  MV: "dv",
  ML: "fr",
  MT: "mt",
  MH: "en",
  MR: "ar",
  MU: "en",
  MX: "es",
  FM: "en",
  MD: "ro",
  MC: "fr",
  MN: "mn",
  ME: "sr",
  MA: "ar",
  MZ: "pt",
  MM: "my",
  NA: "en",
  NR: "en",
  NP: "ne",
  NL: "nl",
  NZ: "en",
  NI: "es",
  NE: "fr",
  NG: "en",
  MK: "mk",
  NO: "no",
  OM: "ar",
  PK: "ur",
  PW: "en",
  PA: "es",
  PG: "en",
  PY: "es",
  PE: "es",
  PH: "tl",
  PL: "pl",
  PT: "pt",
  QA: "ar",
  RO: "ro",
  RU: "ru",
  RW: "rw",
  KN: "en",
  LC: "en",
  VC: "en",
  WS: "sm",
  SM: "it",
  ST: "pt",
  SA: "ar",
  SN: "fr",
  RS: "sr",
  SC: "fr",
  SL: "en",
  SG: "en",
  SK: "sk",
  SI: "sl",
  SB: "en",
  SO: "so",
  ZA: "en",
  SS: "en",
  ES: "es",
  LK: "si",
  SD: "ar",
  SR: "nl",
  SE: "sv",
  CH: "de",
  SY: "ar",
  TW: "zh",
  TJ: "tg",
  TZ: "sw",
  TH: "th",
  TL: "pt",
  TG: "fr",
  TO: "en",
  TT: "en",
  TN: "ar",
  TR: "tr",
  TM: "tk",
  TV: "en",
  UG: "en",
  UA: "uk",
  AE: "ar",
  GB: "en",
  US: "en",
  UY: "es",
  UZ: "uz",
  VU: "bi",
  VE: "es",
  VN: "vi",
  YE: "ar",
  ZM: "en",
  ZW: "en",
};
