export const GENRES: Record<string, { label: string; color: string }> = {
  act: { label: "Action", color: "red" },
  adv: { label: "Adventure", color: "green" },
  ani: { label: "Animation", color: "pink" },
  bio: { label: "Biography", color: "blue" },
  cmy: { label: "Comedy", color: "yellow" },
  crm: { label: "Crime", color: "gray" },
  doc: { label: "Documentary", color: "teal" },
  drm: { label: "Drama", color: "indigo" },
  fml: { label: "Family", color: "orange" },
  fnt: { label: "Fantasy", color: "violet" },
  hst: { label: "History", color: "cyan" },
  hrr: { label: "Horror", color: "darkred" },
  msc: { label: "Music", color: "lime" },
  mys: { label: "Mystery", color: "grape" },
  rma: { label: "Romance", color: "lightpink" },
  scf: { label: "Science Fiction", color: "blue" },
  spt: { label: "Sports", color: "lime" },
  trl: { label: "Thriller", color: "darkblue" },
  war: { label: "War", color: "maroon" },
  wsn: { label: "Western", color: "brown" },
  eur: { label: "Made in Europe", color: "darkgreen" },
  rly: { label: "Reality", color: "lightcoral" },
};
